-- 1. 기존 테이블 삭제
DROP TABLE BOARD;

-- 2. STATUS 컬럼이 포함된 새 구조 생성
CREATE TABLE BOARD (
    NOTICE_NO    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    TITLE        VARCHAR2(200) NOT NULL,
    CONTENT      CLOB          NOT NULL,
    WRITER       VARCHAR2(50)  NOT NULL,
    BOARD_TYPE   VARCHAR2(20)  NOT NULL, -- 'NOTICE', 'QNA'
    COUNT        NUMBER DEFAULT 0,
    INDATE       DATE DEFAULT SYSDATE,
    PARENT_NO    NUMBER DEFAULT 0,       -- 원글 번호
    IS_REPLY     NUMBER DEFAULT 0,       -- 답변 여부 (0: 원글, 1: 답변)
    STATUS       VARCHAR2(10) DEFAULT 'Y' -- 게시 상태 ('Y': 게시중, 'N': 숨김)
);

-- 3. QNA 테스트 데이터 생성 (101건)
BEGIN
    FOR i IN 1..101 LOOP
        INSERT INTO BOARD (TITLE, CONTENT, WRITER, BOARD_TYPE, PARENT_NO, IS_REPLY, STATUS)
        VALUES (
            '서비스 이용 관련 문의드립니다 ' || i, 
            '내용: 로그인 장애 관련 상세 문의 내용입니다. 번호: ' || i, 
            'user' || i, 
            'QNA', 
            0, 
            0, 
            CASE WHEN MOD(i, 10) = 0 THEN 'N' ELSE 'Y' END -- 10번째마다 숨김 처리
        );
    END LOOP;
    COMMIT;
END;
/

-- 4. 공지사항 테스트 데이터 생성 (101건)
BEGIN
    FOR i IN 1..101 LOOP
        INSERT INTO BOARD (TITLE, CONTENT, WRITER, BOARD_TYPE, PARENT_NO, IS_REPLY, STATUS)
        VALUES (
            '[공지] 시스템 정기 점검 안내 (' || i || ')', 
            '안녕하세요. 관리자입니다. 시스템 안정화를 위한 점검 안내문입니다. 번호: ' || i, 
            '관리자', 
            'NOTICE', 
            0, 
            0, 
            CASE WHEN MOD(i, 20) = 0 THEN 'N' ELSE 'Y' END -- 20번째마다 숨김 처리
        );
    END LOOP;
    COMMIT;
END;
/

-- 데이터 확인용 쿼리
SELECT NOTICE_NO, TITLE, BOARD_TYPE, STATUS 
FROM BOARD 
WHERE NOTICE_NO > 195;