CREATE TABLE CRAWL_CONFIG (
    SITE_ID         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    SITE_NAME       VARCHAR2(100) NOT NULL, -- 예: 'HotdealZip'
    TARGET_URL      VARCHAR2(500),          -- 크롤링 대상 주소
    CRON_EXPRESSION VARCHAR2(50),           -- 스케줄링 주기 (예: 0 0 0/6 * * ?)
    IS_ACTIVE       CHAR(1) DEFAULT 'Y',    -- 작동 여부 (Y/N)
    LAST_RUN_DATE   DATE,                   -- 마지막 실행 시각
    UPDATE_DATE     DATE DEFAULT SYSDATE
);

-- 초기 데이터
INSERT INTO CRAWL_CONFIG (SITE_NAME, TARGET_URL, CRON_EXPRESSION) 
VALUES ('HotdealZip', 'https://hotdeal.zip/', '0 0 0/6 * * ?');