CREATE TABLE TB_HOTDEAL_TRACKER (
    DEAL_ID NUMBER PRIMARY KEY,
    ORIGIN_URL VARCHAR2(500) UNIQUE, -- 게시글 주소를 PK 대용(Unique)으로 활용
    TITLE VARCHAR2(300),
    CURRENT_PRICE NUMBER,
    START_PRICE NUMBER,              -- 최초 수집 가격
    MALL_NAME VARCHAR2(100),         -- 쇼핑몰(11번가, 쿠팡 등)
    COMMUNITY_NAME VARCHAR2(100),    -- 출처(에펨코리아, 뽐뿌 등)
    LAST_UPDATE_DATE DATE DEFAULT SYSDATE
);

-- 가격 변동 이력을 저장할 테이블 (차트 구현용)
CREATE TABLE TB_PRICE_HISTORY (
    HISTORY_ID NUMBER PRIMARY KEY,
    DEAL_ID NUMBER REFERENCES TB_HOTDEAL_TRACKER(DEAL_ID),
    PRICE NUMBER,
    RECORD_DATE DATE DEFAULT SYSDATE
);