-- 1. 기존 테이블 및 제약 조건 삭제
DROP TABLE PRICE_HISTORY CASCADE CONSTRAINTS;
DROP TABLE Common_Product CASCADE CONSTRAINTS;

-- 2. 통합 상품 정보 테이블
-- 실시간 크롤링 데이터와 일반 상품 데이터를 모두 수용하도록 컬럼 확장
CREATE TABLE Common_Product (
    PROD_ID         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, 
    PROD_CODE       VARCHAR2(50) NOT NULL,      -- 중복 체크용 고유 키 (URL 또는 고유코드)
    SOURCE          VARCHAR2(50),               -- 출처 (NAVER, COUPANG, 또는 게시판 작성자)
    CATEGORY        VARCHAR2(50),               
    PROD_NAME       VARCHAR2(500) NOT NULL,     -- 크롤링 시 제목이 길 수 있으므로 확장
    BRAND           VARCHAR2(100),              
    PROD_PRICE      NUMBER DEFAULT 0,           -- 현재가
    TARGET_PRICE    NUMBER,                    
    CHECK_INTERVAL  NUMBER DEFAULT 6,         
    
    -- 크롤링 및 통합 조회를 위한 필수 필드 추가
    IMAGE_URL       VARCHAR2(1000),             -- 상품/게시글 이미지
    ORIGIN_URL      VARCHAR2(1000),             -- 원문 링크
    BOARD_TYPE      VARCHAR2(20) DEFAULT 'NORMAL', -- 'NORMAL', 'HOT', 'CRAWL' 구분
    
    REG_DATE        DATE DEFAULT SYSDATE,
    
    CONSTRAINT UK_PROD_CODE UNIQUE (PROD_CODE)
);

-- 3. 가격 변동 이력 테이블
CREATE TABLE PRICE_HISTORY (
    HIST_ID      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    PROD_ID      NUMBER NOT NULL,            
    PRICE        NUMBER NOT NULL,            
    REG_DATE     DATE DEFAULT SYSDATE,       
    CONSTRAINT FK_HIST_PROD_ID FOREIGN KEY (PROD_ID) 
    REFERENCES Common_Product(PROD_ID) ON DELETE CASCADE
);

-- 4. 초기 테스트 데이터 삽입
-- 기존 데이터 삭제 (중복 방지)
DELETE FROM PRICE_HISTORY;
DELETE FROM Common_Product;

BEGIN
    -- [1] IT/가전/PC (하락폭이 커서 연출하기 좋음)
    INSERT INTO Common_Product (PROD_CODE, SOURCE, CATEGORY, PROD_NAME, PROD_PRICE, BOARD_TYPE)
    VALUES ('HOT_PC_01', '네이버', 'PC', '마이크로소프트 서피스 프로 12 Plus', 2300000, 'HOT');
    
    INSERT INTO Common_Product (PROD_CODE, SOURCE, CATEGORY, PROD_NAME, PROD_PRICE, BOARD_TYPE)
    VALUES ('HOT_PC_02', '쿠팡', 'PC', 'LG전자 울트라기어 27GS60QC', 490000, 'HOT');
    
    INSERT INTO Common_Product (PROD_CODE, SOURCE, CATEGORY, PROD_NAME, PROD_PRICE, BOARD_TYPE)
    VALUES ('HOT_PC_03', 'futureteri', 'PC', '앤커 랩탑 파워뱅크 25000mAh', 180000, 'HOT');
    
    INSERT INTO Common_Product (PROD_CODE, SOURCE, CATEGORY, PROD_NAME, PROD_PRICE, BOARD_TYPE)
    VALUES ('HOT_APP_01', '컴퓨존', '가전', '갤럭시탭 S11 WIFI 128GB', 2100000, 'HOT');
    
    INSERT INTO Common_Product (PROD_CODE, SOURCE, CATEGORY, PROD_NAME, PROD_PRICE, BOARD_TYPE)
    VALUES ('HOT_APP_02', '11번가', '가전', '삼성 25년형 무풍클래식 에어컨', 3800000, 'HOT');
    
    INSERT INTO Common_Product (PROD_CODE, SOURCE, CATEGORY, PROD_NAME, PROD_PRICE, BOARD_TYPE)
    VALUES ('HOT_APP_03', '오늘의집', '가전', '필립스 전자동 커피머신 EP1220/19', 580000, 'HOT');

    -- [2] 식품류 (리스트에 많았던 품목)
    INSERT INTO Common_Product (PROD_CODE, SOURCE, CATEGORY, PROD_NAME, PROD_PRICE, BOARD_TYPE)
    VALUES ('HOT_FOOD_01', '롯데온', '식품', '암꽃게 1kg 4-6미', 50000, 'HOT');
    
    INSERT INTO Common_Product (PROD_CODE, SOURCE, CATEGORY, PROD_NAME, PROD_PRICE, BOARD_TYPE)
    VALUES ('HOT_FOOD_02', '옥션', '식품', '프로즌 곱도리탕 1+1 (590g 2팩)', 32000, 'HOT');
    
    INSERT INTO Common_Product (PROD_CODE, SOURCE, CATEGORY, PROD_NAME, PROD_PRICE, BOARD_TYPE)
    VALUES ('HOT_FOOD_03', '네이버', '식품', '한우등심1등급 500g', 75000, 'HOT');
    
    INSERT INTO Common_Product (PROD_CODE, SOURCE, CATEGORY, PROD_NAME, PROD_PRICE, BOARD_TYPE)
    VALUES ('HOT_FOOD_04', '지마켓', '식품', '청정원 순창 초고추장 1kg 3통', 22000, 'HOT');
    
    INSERT INTO Common_Product (PROD_CODE, SOURCE, CATEGORY, PROD_NAME, PROD_PRICE, BOARD_TYPE)
    VALUES ('HOT_FOOD_05', '11번가', '식품', '토레타 340ml 24개', 24000, 'HOT');
    
    INSERT INTO Common_Product (PROD_CODE, SOURCE, CATEGORY, PROD_NAME, PROD_PRICE, BOARD_TYPE)
    VALUES ('HOT_FOOD_06', '롯데온', '식품', '코카콜라 제로 350ml 24캔', 32000, 'HOT');
    
    INSERT INTO Common_Product (PROD_CODE, SOURCE, CATEGORY, PROD_NAME, PROD_PRICE, BOARD_TYPE)
    VALUES ('HOT_FOOD_07', '지마켓', '식품', '배홍동 8개 + 안성탕면 5개 + 짜파게티 5개', 28000, 'HOT');

    -- [3] 생활/의류/기타
    INSERT INTO Common_Product (PROD_CODE, SOURCE, CATEGORY, PROD_NAME, PROD_PRICE, BOARD_TYPE)
    VALUES ('HOT_LIFE_01', '롯데온', '생활용품', '도루코 페이스6 면도날 12입', 45000, 'HOT');
    
    INSERT INTO Common_Product (PROD_CODE, SOURCE, CATEGORY, PROD_NAME, PROD_PRICE, BOARD_TYPE)
    VALUES ('HOT_LIFE_02', '지마켓', '생활용품', '지오다노 장우산', 30000, 'HOT');
    
    INSERT INTO Common_Product (PROD_CODE, SOURCE, CATEGORY, PROD_NAME, PROD_PRICE, BOARD_TYPE)
    VALUES ('HOT_LIFE_03', '지마켓', '생활용품', '렛츠클린 다용도 건티슈 대형 200매', 14000, 'HOT');
    
    INSERT INTO Common_Product (PROD_CODE, SOURCE, CATEGORY, PROD_NAME, PROD_PRICE, BOARD_TYPE)
    VALUES ('HOT_CLOTH_01', '지마켓', '의류', '푸마 단목양말 10켤레', 28000, 'HOT');
    
    INSERT INTO Common_Product (PROD_CODE, SOURCE, CATEGORY, PROD_NAME, PROD_PRICE, BOARD_TYPE)
    VALUES ('HOT_CLOTH_02', 'SSG', '의류', '레노마 봄 여름 프리미엄 정장', 180000, 'HOT');
    
    INSERT INTO Common_Product (PROD_CODE, SOURCE, CATEGORY, PROD_NAME, PROD_PRICE, BOARD_TYPE)
    VALUES ('HOT_CLOTH_03', '롯데온', '의류', '폴햄 기본 캐쥬얼 니트', 25000, 'HOT');
    
    INSERT INTO Common_Product (PROD_CODE, SOURCE, CATEGORY, PROD_NAME, PROD_PRICE, BOARD_TYPE)
    VALUES ('HOT_ETC_01', 'SSG', 'PC', '로지텍 G304 무선 게이밍 마우스', 75000, 'HOT');

    COMMIT;
END;
/

-- 4. 위 상품들의 '비싼 가격'을 과거 이력으로 1회 강제 저장
INSERT INTO PRICE_HISTORY (PROD_ID, PRICE, REG_DATE)
SELECT PROD_ID, PROD_PRICE, SYSDATE - 1 FROM Common_Product;

COMMIT;

-- 데이터 확인
SELECT COUNT(*) FROM Common_Product;
SELECT * FROM (SELECT * FROM Common_Product ORDER BY REG_DATE DESC) WHERE ROWNUM <= 10;
SELECT * FROM PRICE_HISTORY;
SELECT * FROM PRICE_HISTORY WHERE PROD_ID = 117;
SELECT * FROM Common_Product;
SELECT IMAGE_URL FROM Common_Product WHERE PROD_ID = 81;
COMMIT;