-- 1. 기존 테이블 및 제약 조건 삭제
DROP TABLE PRICE_HISTORY CASCADE CONSTRAINTS;
DROP TABLE Common_Product CASCADE CONSTRAINTS;

-- 2. 통합 상품 정보 테이블
-- 실시간 크롤링 데이터와 일반 상품 데이터를 모두 수용하도록 컬럼 확장
CREATE TABLE Common_Product (
    PROD_ID         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, 
    PROD_CODE       VARCHAR2(50) NOT NULL,      -- 중복 체크용 고유 키 (URL 또는 고유코드)
    SOURCE          VARCHAR2(50),               -- 출처 (NAVER, COUPANG, 또는 게시판 작성자)
    CATEGORY        VARCHAR2(50),               
    PROD_NAME       VARCHAR2(500) NOT NULL,     -- 크롤링 시 제목이 길 수 있으므로 확장
    BRAND           VARCHAR2(100),              
    PROD_PRICE      NUMBER DEFAULT 0,           -- 현재가
    TARGET_PRICE    NUMBER,                    
    CHECK_INTERVAL  NUMBER DEFAULT 6,         
    
    -- 크롤링 및 통합 조회를 위한 필수 필드 추가
    IMAGE_URL       VARCHAR2(1000),             -- 상품/게시글 이미지
    ORIGIN_URL      VARCHAR2(1000),             -- 원문 링크
    BOARD_TYPE      VARCHAR2(20) DEFAULT 'NORMAL', -- 'NORMAL', 'HOT', 'CRAWL' 구분
    
    REG_DATE        DATE DEFAULT SYSDATE,
    
    CONSTRAINT UK_PROD_CODE UNIQUE (PROD_CODE)
);

-- 3. 가격 변동 이력 테이블
CREATE TABLE PRICE_HISTORY (
    HIST_ID      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    PROD_ID      NUMBER NOT NULL,            
    PRICE        NUMBER NOT NULL,            
    REG_DATE     DATE DEFAULT SYSDATE,       
    CONSTRAINT FK_HIST_PROD_ID FOREIGN KEY (PROD_ID) 
    REFERENCES Common_Product(PROD_ID) ON DELETE CASCADE
);

-- 4. 초기 테스트 데이터 삽입
-- [RTX 3090]
INSERT INTO Common_Product (PROD_CODE, SOURCE, CATEGORY, PROD_NAME, BRAND, PROD_PRICE, BOARD_TYPE, ORIGIN_URL) 
VALUES ('NV-3090', 'NAVER', 'PC부품', 'NVIDIA GeForce RTX 3090 Ti', 'NVIDIA', 1850000, 'DROP', 'https://naver.com/item1');

-- [맥북]
INSERT INTO Common_Product (PROD_CODE, SOURCE, CATEGORY, PROD_NAME, BRAND, PROD_PRICE, BOARD_TYPE, ORIGIN_URL) 
VALUES ('AP-MBP16', 'COUPANG', '노트북', 'Apple 맥북 프로 16 M3 Max', 'Apple', 4850000, 'NORMAL', 'https://coupang.com/item2');

-- [소니 헤드셋]
INSERT INTO Common_Product (PROD_CODE, SOURCE, CATEGORY, PROD_NAME, BRAND, PROD_PRICE, BOARD_TYPE, ORIGIN_URL) 
VALUES ('SN-XM5', 'SSG', '음향기기', '소니 WH-1000XM5 헤드셋', 'SONY', 360000, 'NORMAL', 'https://ssg.com/item3');

-- 5. 가격 이력 등록 (PROD_ID 기반)
-- RTX 3090
INSERT INTO PRICE_HISTORY (PROD_ID, PRICE, REG_DATE) VALUES (1, 2200000, SYSDATE - 1);
INSERT INTO PRICE_HISTORY (PROD_ID, PRICE, REG_DATE) VALUES (1, 1850000, SYSDATE);

-- 맥북
INSERT INTO PRICE_HISTORY (PROD_ID, PRICE, REG_DATE) VALUES (2, 4800000, SYSDATE - 1);
INSERT INTO PRICE_HISTORY (PROD_ID, PRICE, REG_DATE) VALUES (2, 4850000, SYSDATE);

-- 소니 헤드셋
INSERT INTO PRICE_HISTORY (PROD_ID, PRICE, REG_DATE) VALUES (3, 450000, SYSDATE - 5);
INSERT INTO PRICE_HISTORY (PROD_ID, PRICE, REG_DATE) VALUES (3, 400000, SYSDATE - 2);
INSERT INTO PRICE_HISTORY (PROD_ID, PRICE, REG_DATE) VALUES (3, 360000, SYSDATE);

-- 6. 페이징 테스트용 대량 데이터 (12개 추가)
BEGIN
    FOR i IN 1..12 LOOP
        INSERT INTO Common_Product (PROD_CODE, PROD_NAME, PROD_PRICE, BOARD_TYPE, REG_DATE)
        VALUES ('PCODE_' || i, '실시간 요청 크롤링 상품 ' || i, 10000 * i, 'CRAWL', SYSDATE - (i/24));
    END LOOP;
    COMMIT;
END;
/

BEGIN
    -- 1. 전자기기/노트북 카테고리 (15개)
    FOR i IN 1..15 LOOP
        INSERT INTO Common_Product (PROD_CODE, SOURCE, CATEGORY, PROD_NAME, BRAND, PROD_PRICE, BOARD_TYPE, ORIGIN_URL, REG_DATE)
        VALUES (
            'LAPTOP_' || i, 
            CASE MOD(i, 3) WHEN 0 THEN 'NAVER' WHEN 1 THEN 'COUPANG' ELSE 'DANWA' END,
            '노트북',
            CASE MOD(i, 3) WHEN 0 THEN '삼성 갤럭시북 4 Pro ' || i WHEN 1 THEN 'LG 그램 16 ' || i ELSE 'ASUS 제피러스 ' || i END,
            CASE MOD(i, 3) WHEN 0 THEN 'Samsung' WHEN 1 THEN 'LG' ELSE 'ASUS' END,
            1200000 + (i * 50000),
            CASE WHEN i <= 5 THEN 'DROP' WHEN i <= 10 THEN 'HOT' ELSE 'NORMAL' END,
            'https://search.shopping.naver.com/search/all?query=laptop' || i,
            SYSDATE - (i/24)
        );
    END LOOP;

    -- 2. 스마트폰/태블릿 카테고리 (15개)
    FOR i IN 16..30 LOOP
        INSERT INTO Common_Product (PROD_CODE, SOURCE, CATEGORY, PROD_NAME, BRAND, PROD_PRICE, BOARD_TYPE, ORIGIN_URL, REG_DATE)
        VALUES (
            'PHONE_' || i,
            CASE MOD(i, 2) WHEN 0 THEN 'SKT' ELSE 'KT' END,
            '스마트폰',
            CASE MOD(i, 2) WHEN 0 THEN '아이폰 15 Pro ' || i ELSE '갤럭시 S24 울트라 ' || i END,
            CASE MOD(i, 2) WHEN 0 THEN 'Apple' ELSE 'Samsung' END,
            1000000 + (i * 20000),
            CASE WHEN i <= 20 THEN 'HOT' WHEN i <= 25 THEN 'CRAWL' ELSE 'NORMAL' END,
            'https://www.apple.com/iphone' || i,
            SYSDATE - (i/48)
        );
    END LOOP;

    -- 3. 가전/생활 카테고리 (10개)
    FOR i IN 31..40 LOOP
        INSERT INTO Common_Product (PROD_CODE, SOURCE, CATEGORY, PROD_NAME, BRAND, PROD_PRICE, BOARD_TYPE, ORIGIN_URL, REG_DATE)
        VALUES (
            'LIFE_' || i,
            'SSG',
            '생활가전',
            '다이슨 에어랩 멀티 스타일러 ' || i,
            'Dyson',
            500000 + (i * 10000),
            'NORMAL',
            'https://www.ssg.com/item/dyson' || i,
            SYSDATE - (i/12)
        );
    END LOOP;

    -- 4. 기타/실시간 크롤링 데이터 (10개)
    FOR i IN 41..50 LOOP
        INSERT INTO Common_Product (PROD_CODE, SOURCE, CATEGORY, PROD_NAME, BRAND, PROD_PRICE, BOARD_TYPE, ORIGIN_URL, REG_DATE)
        VALUES (
            'CRAWL_' || i,
            'CRAWLER',
            '기타',
            '실시간 핫딜 정보 상품 ' || i,
            'ETC',
            10000 * i,
            'CRAWL',
            'https://hotdeal.com/item' || i,
            SYSDATE - (i/100)
        );
    END LOOP;

    COMMIT;
END;

-- 데이터 확인
SELECT COUNT(*) FROM Common_Product;
SELECT * FROM (SELECT * FROM Common_Product ORDER BY REG_DATE DESC) WHERE ROWNUM <= 10;

COMMIT;